- id: shell-lint
  name: Shell Syntax Check
  description: Check Shell Syntax on ALL staged files with user friendly messages and colors
  entry: pre_commit_hooks/shell-lint.sh
  language: script
- id: hadolint
  name: Hadolint
  description: Haskell-based Docker image linter
  language: docker_image
  types:
  - dockerfile
  entry: --entrypoint /bin/hadolint hadolint/hadolint:latest --ignore DL3013 --ignore DL3018 --ignore DL3008 -
