version: 2

defaults: &defaults
  docker:
    - image: docker:19.03.3-git

jobs:

  docker-build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: docker build -t dotfilez -t $CIRCLE_SHA1 .
      - run:
          name: tag and push docker image
          environment:
            DOCKER_ORG: burdz/private
            REPO_TAG: dotfilez
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag $CIRCLE_SHA1 $DOCKER_ORG:$CIRCLE_SHA1
              docker tag $CIRCLE_SHA1 $DOCKER_ORG:$REPO_TAG
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push $DOCKER_ORG:$CIRCLE_SHA1
              docker push $DOCKER_ORG:$REPO_TAG
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - docker-build
