version: 2

defaults: &defaults
  docker:
    - image: docker:19.03.3-git

jobs:

  docker-build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: docker build -t dotfilez -t $CIRCLE_SHA1 .
      - run:
          name: tag and push docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag $CIRCLE_SHA1 burdz/private:$CIRCLE_SHA1
              docker tag $CIRCLE_SHA1 burdz/private:dotfilez
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push burdz/private:$CIRCLE_SHA1
              docker push burdz/private:dotfilez
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - docker-build
