# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zpool/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zpool/home";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "zpool/var";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zpool/nix";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # services.autorandr = {
  #   enable = true;     
  #   profiles = {       
  #     "desktop" = {         
  #       fingerprint = {           
  #         DP-4 = "00ffffffffffff001e6d7b9ee07902000a1f0104b57822789e09c1ae5044af260e50542108007140818081c0a9c0d1c0810001010101a6780030f2385a40b0588a00ae514100001e023a801871382d40582c4500ae514100001e000000fd00303d1e873c000a202020202020000000fc004c472048445220445148440a2002240203197144010304902309070783010000e305c000e30605014dd000a0f0703e803020650c204a3100001a286800a0f0703e800890650c204a3100001a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e3701279030003002845b70088ff139f002f801f009f05280002000900655a0088ff139f002f8014009f05140002000900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ef90";           
  #         HDMI-0 = "00ffffffffffff001e6dd776ca710900031a010380502278eaca95a6554ea1260f50542108007140818081c0a9c0b300d1c0810001019d6770a0d0a0225030203a00204f3100001a000000fd00383d1e5a1e000a202020202020000000fc003334554d39350a20202020202000000000000000000000000000000000000001bd020317f14410040301230907078301000065030c0010009f3d70a0d0a0155030203a00204f3100001a7e4800e0a0381f4040403a00204f31000018011d007251d01e206e285500204f3100001e8c0ad08a20e02d10103e9600204f31000018000000ff003630334e5459544a363935340a00000000000000000000000000008d";           
  #         HDMI-1 = "00ffffffffffff001e6df676c2bd0000081d010380502278eaca95a6554ea1260f50542108007140818081c0a9c0b300d1c081000101e77c70a0d0a0295030203a00204f3100001a9d6770a0d0a0225030203a00204f3100001a000000fd00383d1e5a20000a202020202020000000fc004c4720554c545241574944450a018c02031ef12309070749100403011f13595a128301000067030c00100038409f3d70a0d0a0155030203a00204f3100001a7e4800e0a0381f4040403a00204f31000018011d007251d01e206e285500204f3100001e8c0ad08a20e02d10103e9600204f31000018000000ff003930384e54595431453537380a0000000000000010";       
  #       };         
  #       config = {           
  #         DP-4 = {             
  #           enable = true;             
  #           crtc = 0;             
  #           primary = true;             
  #           position = "3440x1440";             
  #           mode = "5120x1440";             
  #           rate = "60.00";           
  #         };           
  #         HDMI-0 = {             
  #           enable = true;             
  #           crtc = 1;             
  #           mode = "3440x1440";             
  #           rate = "60.00";             
  #           primary = false;             
  #           position = "0x1440";           
  #         };           
  #         HDMI-1 = {             
  #           enable = true;             
  #           crtc = 2;             
  #           mode = "3440x1440";             
  #           rate = "60.00";             
  #           primary = false;             
  #           position = "0x0";           
  #         };         
  #       };       
  #     };     
  #   };   
  # }; 


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp68s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp71s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp72s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
