on:
  pull_request_review_comment:
    types: [created]
name: bump submodulez
jobs:
  bumpModules:
    name: bumpy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: bump git submodulez
      uses: domdere/git-submodule-action@0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
