on:
  issue_comment:
    types: [created, edited]
name: bump submodulez
jobs:
  bumpModules:
    name: bumpy
    if: contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: bump git submodulez
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - name: commit deez submodulez
      if: contains(github.event.comment.body, '/bumpy')
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions - update submodules"
        git add --all
        git commit -m "Update submodules" || echo "No changes to commit"
        git push
